version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend-network
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306"  
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - ConnectionString__MySQLConnection=Server=mysql;Database=${MYSQL_DATABASE};User=${MYSQL_USER};Password=${MYSQL_PASSWORD};
    networks:
      - backend-network
    ports:
      - "5028:8080" 
    depends_on:
      - mysql
    restart: unless-stopped
  image-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-backend
    ports:
      - "5299:8081"
    volumes:
      - images-data:/app/images
    restart: unless-stopped
networks:
  backend-network:
    driver: bridge  
volumes:
  mysql-data: {}  
  images-data: {}  